CREATE TABLE try_on_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL,
    source_url VARCHAR(2048),
    source_kind VARCHAR(30) NOT NULL,
    image_object_key VARCHAR(500) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_try_on_favorites_user_image UNIQUE (user_id, fingerprint)
);
CREATE INDEX idx_try_on_favorites_user_created ON try_on_favorites(user_id, created_at DESC, id DESC);
