CREATE TABLE IF NOT EXISTS app_users (
    username VARCHAR(32) PRIMARY KEY,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS app_authorities (
    username VARCHAR(32) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    PRIMARY KEY (username, authority),
    CONSTRAINT fk_app_authorities_user
        FOREIGN KEY (username) REFERENCES app_users (username) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wardrobe_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(40) NOT NULL,
    color VARCHAR(40) NOT NULL,
    style VARCHAR(120),
    image_url VARCHAR(500),
    image_object_key VARCHAR(300),
    recognition_status VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    recognition_message VARCHAR(240),
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE wardrobe_items ADD COLUMN IF NOT EXISTS image_object_key VARCHAR(300);
ALTER TABLE wardrobe_items ADD COLUMN IF NOT EXISTS recognition_status VARCHAR(32) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE wardrobe_items ADD COLUMN IF NOT EXISTS recognition_message VARCHAR(240);

CREATE TABLE IF NOT EXISTS style_profiles (
    user_id VARCHAR(100) PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    style_preferences TEXT NOT NULL,
    color_preferences TEXT NOT NULL,
    occasion_preferences TEXT NOT NULL,
    style_tags TEXT NOT NULL,
    try_style_tags TEXT NOT NULL,
    color_suggestions TEXT NOT NULL,
    item_suggestions TEXT NOT NULL,
    reason_summary VARCHAR(1200) NOT NULL,
    model_name VARCHAR(160) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    occasion VARCHAR(80) NOT NULL,
    city VARCHAR(80) NOT NULL,
    temperature_c DECIMAL(5, 2),
    summary VARCHAR(500) NOT NULL,
    reason VARCHAR(1200) NOT NULL,
    engine VARCHAR(80) NOT NULL,
    weather_apparent_temperature_c DECIMAL(5, 2),
    weather_precipitation_mm DECIMAL(6, 2),
    weather_code INT,
    weather_wind_speed_kmh DECIMAL(6, 2),
    weather_observed_at TIMESTAMP,
    weather_source VARCHAR(100),
    saved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS weather_apparent_temperature_c DECIMAL(5, 2);
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS weather_precipitation_mm DECIMAL(6, 2);
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS weather_code INT;
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS weather_wind_speed_kmh DECIMAL(6, 2);
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS weather_observed_at TIMESTAMP;
ALTER TABLE recommendations ADD COLUMN IF NOT EXISTS weather_source VARCHAR(100);

CREATE TABLE IF NOT EXISTS recommendation_items (
    recommendation_id BIGINT NOT NULL,
    position_no INT NOT NULL,
    wardrobe_item_id BIGINT,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(40) NOT NULL,
    color VARCHAR(40) NOT NULL,
    style VARCHAR(120),
    image_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (recommendation_id, position_no),
    CONSTRAINT fk_recommendation_items_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES recommendations (id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendation_items_wardrobe
        FOREIGN KEY (wardrobe_item_id) REFERENCES wardrobe_items (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS recommendation_feedback (
    recommendation_id BIGINT NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    rating INT NOT NULL,
    feedback_type VARCHAR(80),
    comment VARCHAR(500),
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (recommendation_id, user_id),
    CONSTRAINT fk_recommendation_feedback_recommendation
        FOREIGN KEY (recommendation_id) REFERENCES recommendations (id) ON DELETE CASCADE,
    CONSTRAINT chk_recommendation_feedback_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_wardrobe_items_user_created_id
    ON wardrobe_items (user_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_recommendations_user_created_id
    ON recommendations (user_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_recommendation_items_wardrobe_item
    ON recommendation_items (wardrobe_item_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_feedback_user_recommendation
    ON recommendation_feedback (user_id, recommendation_id);

DROP INDEX IF EXISTS idx_wardrobe_items_user_id;
DROP INDEX IF EXISTS idx_recommendations_user_id;
