-- Administrator governance data.
-- Feedback status is separate from the user's rating/comment so moderation never
-- changes the user's original product feedback.
ALTER TABLE recommendation_feedback
    ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(16) NOT NULL DEFAULT 'PENDING';
ALTER TABLE recommendation_feedback
    ADD COLUMN IF NOT EXISTS handled_by VARCHAR(32);
ALTER TABLE recommendation_feedback
    ADD COLUMN IF NOT EXISTS handled_at TIMESTAMP;

ALTER TABLE recommendation_feedback
    ADD CONSTRAINT chk_recommendation_feedback_moderation_status
    CHECK (moderation_status IN ('PENDING', 'REVIEWED', 'RESOLVED'));

CREATE INDEX IF NOT EXISTS idx_recommendation_feedback_moderation_status
    ON recommendation_feedback (moderation_status, updated_at, recommendation_id);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username VARCHAR(32) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id VARCHAR(160),
    outcome VARCHAR(24) NOT NULL,
    details VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_id
    ON admin_audit_logs (created_at, id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_action_outcome
    ON admin_audit_logs (action, outcome, created_at, id);
