package com.fashion.recommendation;

import java.util.List;
import java.util.Locale;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.output.MigrateResult;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.junit.jupiter.api.Assertions.assertEquals;

class FlywayMigrationTest {
    private static final List<String> V1_INDEXES = List.of(
            "idx_wardrobe_items_user_created_id",
            "idx_recommendations_user_created_id",
            "idx_recommendation_items_wardrobe_item",
            "idx_recommendation_feedback_user_recommendation");

    @Test
    void upgradesANonEmptyLegacySchemaOnceWithoutLosingExistingData() {
        JdbcDataSource dataSource = legacyDataSource();
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        createLegacySchema(jdbcTemplate);
        Flyway flyway = Flyway.configure()
                .dataSource(dataSource)
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .cleanDisabled(true)
                .load();

        MigrateResult firstMigration = flyway.migrate();

        assertEquals(1, firstMigration.migrationsExecuted);
        assertEquals("1", flyway.info().current().getVersion().getVersion());
        assertEquals("旧衣物", jdbcTemplate.queryForObject(
                "SELECT name FROM wardrobe_items WHERE id = 41", String.class));
        assertEquals("MANUAL", jdbcTemplate.queryForObject(
                "SELECT recognition_status FROM wardrobe_items WHERE id = 41", String.class));
        assertEquals(0, jdbcTemplate.queryForObject("SELECT COUNT(*) FROM app_users", Integer.class));
        V1_INDEXES.forEach(indexName -> assertIndexExists(jdbcTemplate, indexName));

        int appliedBeforeRestart = flyway.info().applied().length;
        MigrateResult secondMigration = flyway.migrate();

        assertEquals(0, secondMigration.migrationsExecuted);
        assertEquals(appliedBeforeRestart, flyway.info().applied().length);
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM wardrobe_items WHERE id = 41 AND name = '旧衣物'", Integer.class));
    }

    private static JdbcDataSource legacyDataSource() {
        JdbcDataSource dataSource = new JdbcDataSource();
        String databaseName = "flyway_upgrade_" + UUID.randomUUID().toString().replace("-", "");
        dataSource.setURL("jdbc:h2:mem:" + databaseName + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    private static void createLegacySchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                CREATE TABLE wardrobe_items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id VARCHAR(100) NOT NULL,
                    name VARCHAR(120) NOT NULL,
                    category VARCHAR(40) NOT NULL,
                    color VARCHAR(40) NOT NULL,
                    style VARCHAR(120),
                    image_url VARCHAR(500),
                    created_at TIMESTAMP NOT NULL
                )
                """);
        jdbcTemplate.update("""
                INSERT INTO wardrobe_items (id, user_id, name, category, color, created_at)
                VALUES (41, 'legacy-user', '旧衣物', '上装', '灰色', TIMESTAMP '2026-07-20 08:00:00')
                """);
    }

    private static void assertIndexExists(JdbcTemplate jdbcTemplate, String indexName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.INDEXES WHERE UPPER(INDEX_NAME) = ?",
                Integer.class,
                indexName.toUpperCase(Locale.ROOT));
        assertEquals(1, count, "missing index " + indexName);
    }
}
